---
- name: Check variables (RUN ONCE)
  assert:
    that:
      - github_account is defined
      - access_token is defined
      - access_token | length > 0
      - access_token | regex_search('^ghp_')
    fail_msg: "access_token was not found or invalid"
  run_once: yes
  tags:
    - install
    - uninstall
