---
- name: Get registration token (RUN ONCE)
  uri:
    url: "https://api.github.com/repos/{{ github_account }}/{{ github_repo }}/actions/runners/registration-token"
    headers:
      Authorization: "token {{ access_token }}"
      Accept: "application/vnd.github.v3+json"
    method: POST
    status_code: 201
    force_basic_auth: yes
  register: registration
  run_once: yes
  tags:
    - install
    - uninstall

- name: Check currently registered runners (RUN ONCE)
  uri:
    url: "https://api.github.com/repos/{{ github_account }}/{{ github_repo }}/actions/runners"
    headers:
      Authorization: "token {{ access_token }}"
      Accept: "application/vnd.github.v3+json"
    method: GET
    status_code: 200
    force_basic_auth: yes
  register: registered_runners
  run_once: yes
  tags:
    - install
    - uninstall

- name: Check service facts
  service_facts:
  tags:
    - install
    - uninstall

- name: Combine Github account and repo names
  set_fact:
    svc_name: "{{ github_owner | default(github_account) }}-{{ github_repo }}"
  tags:
    - install
    - uninstall

- name: Build service name
  set_fact:
    runner_service: "actions.runner.{{ svc_name[:45] }}.{{ ansible_hostname }}.service"
  tags:
    - install
    - uninstall