---
- block:
  - name: Get registration token for organization (RUN ONCE)
    uri:
      url: "{{ github_api_url }}/orgs/{{ github_owner | default(github_account) }}/actions/runners/registration-token"
      headers:
        Authorization: "token {{ access_token }}"
        Accept: "application/vnd.github.v3+json"
      method: POST
      status_code: 201
      force_basic_auth: yes
    register: registration
    run_once: yes
    tags:
      - install
      - uninstall

  - name: Check currently registered runners for organization (RUN ONCE)
    uri:
      url: "{{ github_api_url }}/orgs/{{ github_owner | default(github_account) }}/actions/runners"
      headers:
        Authorization: "token {{ access_token }}"
        Accept: "application/vnd.github.v3+json"
      method: GET
      status_code: 200
      force_basic_auth: yes
    check_mode: false
    register: registered_runners
    run_once: yes
    tags:
      - install
      - uninstall

  - name: Check service facts
    service_facts:
    tags:
      - install
      - uninstall

  - name: Build service name
    set_fact:
      runner_service: "actions.runner.{{ ([( github_owner | default(github_account))[:45], runner_name] | join('.'))[:57]  }}.service"
    when: not runner_on_ghes
    tags:
      - install
      - uninstall

  - name: Build service name for GitHub Enterprise Server
    set_fact:
      runner_service: "actions.runner._services.{{ ([( github_owner | default(github_account))[:45], runner_name] | join('.'))[:57]  }}.service"
    when: runner_on_ghes
    tags:
      - install
      - uninstall
