---
- include_tasks: collect_info_org.yml
  when: runner_org
  tags:
    - install
    - uninstall

- include_tasks: collect_info_repo.yml
  when: not runner_org
  tags:
    - install
    - uninstall

- include_tasks: install_deps.yml
  tags:
    - install

- include_tasks: uninstall_runner.yml
  when: uninstall_runner
  tags:
    - uninstall

- include_tasks: install_runner.yml
  tags:
    - install