---
- include_tasks: collect_info.yml
  tags:
    - install
    - uninstall

- include_tasks: install_deps.yml
  tags:
    - install

- include_tasks: uninstall_runner.yml
  when: uninstall_runner
  tags:
    - uninstall

- include_tasks: install_runner.yml
  tags:
    - install