---
- name: Install
  user: ansible
  hosts: all
  become: yes
  vars:
    - runner_user: ansible
    - github_account: monolithprojects-testorg
    - runner_org: yes
    - runner_state: "stopped"
    - runner_version: "2.274.1"
  roles:
    - robertdebock.epel
    - ansible-github_actions_runner

- name: Reinstall
  user: ansible
  hosts: all
  become: yes
  vars:
    - runner_user: ansible
    - github_account: monolithprojects-testorg
    - runner_org: yes
    - reinstall_runner: yes
    - runner_version: "latest"
  roles:
    - robertdebock.epel
    - ansible-github_actions_runner