name: molecule converge tag install/uninstall

on:
    push:
        branches:
            - develop
            - feature/*
    schedule:
        - cron: '0 6 * * 0'
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: Molecule for Ansible - lint
        uses: MonolithProjects/action-molecule@v1.2.0
        with:
          molecule_command: lint    

  test_lifecycle:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      fail-fast: false
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: Molecule for Ansible - converge Default
        uses: MonolithProjects/action-molecule@v1.3.0
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          molecule_command: converge
      - name: Molecule for Ansible - converge tag uninstall
        uses: MonolithProjects/action-molecule@v1.3.0
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          molecule_command: converge
          converge_extra_args: --extra-vars "uninstall_runner=yes" --tags uninstall