name: molecule test

on:
    push:
        branches:
            - master
            - develop
            - feature/*
    schedule:
        - cron: '0 6 * * 0'
jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v2
  #       with:
  #         path: "${{ github.repository }}"
  #     - name: Molecule for Ansible
  #       uses: MonolithProjects/action-molecule@v1.2.0
  #       env:
  #         PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  test_lifecycle:
    runs-on: ubuntu-latest
    # needs: test
    strategy:
      fail-fast: false
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: Molecule for Ansible - converge Default
        uses: MonolithProjects/action-molecule@v1.2.0
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          molecule_command: converge
      - name: Molecule for Ansible - converge tag uninstall
        uses: MonolithProjects/action-molecule@v1.2.0
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          molecule_command: converge
          converge_tags: uninstall