name: molecule test

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
        types: [opened, synchronize, reopened]
    schedule:
        - cron: '0 6 * * 0'
jobs:
  repo:
    name: Test Repo Runner
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: true
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: Molecule for Ansible - GHR Repository
        uses: MonolithProjects/action-molecule@v1.4.0
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          molecule_command: test
  org:
    name: Test Org Runner
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: true
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: Molecule for Ansible - GHR Organization
        uses: MonolithProjects/action-molecule@v1.4.0
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          molecule_command: test
          scenario: organization